### ISSUE TITLE
Мусор после автотестов

### ISSUE THREAD

**Issue by tumb1er** [rutube/php-api-client#2]
http://rutube.ru/video/person/152485/ - 90 никому не нужных видео, оставшихся после автотестов. Плюс порядка 500 скрытых видео.

Предложение - в tearDown удалять все видео, отдаваемые api/video/person/152485/

**Comment by trong** [comment]
Ролики заливаются не только в тестах, но и в примерах - это публичная библиотека, поэтому уборка в конце теста - не панацея. Для того, чтобы весь этот мусор не валялся просто так реализован сервис ежедневной очистки всех роликов тестового пользователя.
