### ISSUE TITLE
Подключение класса без Composer

### ISSUE THREAD

**Issue by 350d** [rutube/php-api-client#3]
Как работать с библиотекой без Composer?

**Comment by trong** [comment]
Библиотека PSR-4 - соответственно подойдет любой автолоадер, поддерживающий этот стандарт.

**Comment by 350d** [comment]
Приложите [autoload.php](https://github.com/facebook/facebook-php-sdk-v4/blob/4.0-dev/autoload.php) как это делает [Facebook](https://github.com/facebook/facebook-php-sdk-v4), например.

**Comment by trong** [comment]
Описали в документации как это сделать
