### ISSUE TITLE
Методы "upload" и "patchVideo"

### ISSUE THREAD

**Issue by 350d** [rutube/php-api-client#4]
Метод `upload` не работает с `https` ссылками.
При обращении к этому методу со следующими параметрами:

``` php
Array
(
    [0] => https://myhost.com/video.mp4
    [1] => title
    [2] => description
    [3] => 0
    [4] => 44
    [5] => https://myhost.com/success.php
    [6] => https://myhost.com/error.php
)
```

Ошибка:

```
Uncaught exception 'Rutube\Exceptions\BadRequestException' with message 'Bad Request'
```

И `body` ответа:

```
Неправильный url
```

`https` не поддерживается и для `callback` параметров. Это ограничение сервиса или ошибка обработки ссылок на сервере?

Длина ссылок ограничена до 512 байт, можно увеличить это значение? Не для всех ссылок этого хватает. Сделайте 2048 байт как минимум [по стандарту](http://stackoverflow.com/a/417184/819764) или включите обработку редиректов, чтоб можно было использовать сокращенные ссылки.

В описании метода пропущен параметр [3] — isHidden. Обновите описание пожалуйста.

В описании метода `patchVideo` ошибочно указан порядок параметров, вторым должен идти `title` и третьим `description`. Не будет лишним указать в описании как можно пропатчить только один параметр у видео, например, только `title`.

**Comment by trong** [comment]
Документацию поправили, спасибо!
С https насколько я знаю разобрались
